a5:	main.o init.o util.o reports.o prints.o
	gcc -o a5 main.o init.o util.o reports.o prints.o

main.o:	main.c defs.h
	gcc -c main.c

init.o:	init.c defs.h
	gcc -c init.c

util.o:	util.c defs.h
	gcc -c util.c

reports.o:	reports.c defs.h
	gcc -c reports.c

prints.o:	prints.c defs.h
	gcc -c prints.c
